name: pr-checks

on:
  pull_request:
    types: [ edited, opened, synchronize, reopened ]
    branches: 
      - 'master'
      - 'main'
      - 'dev'
    paths-ignore:
      - '**.yaml'
      - '**.md'
      - '**.sh'
      - 'website/*'
      - 'examples/*'
      - 'docs/*'
      - 'build/*'
      - '.github/*'
jobs:
  test:
    uses: ./.github/workflows/test.yaml
    with:
      release: "v2.0.${{ github.run_number }}"
      client: test
